version: "3.8"
services:
  postgres:
    container_name: db
    restart: always
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/pg_data
      POSTGRES_DB: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
volumes:
  pgdata:
    driver: local
