name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: golang:1.22.1

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install Docker
      #   run: |
      #     apt-get update
      #     apt-get install -y docker-ce docker-ce-cli containerd.io
      # - name: Check version
      #   run: docker version

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
